### ISSUE TITLE
Android Issues 

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#127]

**Comment by Brahmanathaswami** [comment]
BR Nexus 5; 
-----------
CRASHES/COMPLETE FAILURE

BR: ** Practice** --> Daily Lesson -- Does not render at all. the mobile scroller appears to be created the entire Daily Lesson stack which should show... does not appear at all. App completely locks up. cannot go back. There is no way out, app switcher or home button takes you out, but you come back in and are forced to uninstall! 

BR: **Fun and Games**  Do very long puzzle... battery low, msg came on from the phone I hit cancel, had to go out via home button, hit app icon to resume.. App crashed lost all my work on the long puzzle.

----------
SMALL BUGS

BR: **Surprise:** Goes to Surprise Audio but the navigation bottom bar group disappears. disappears
BR: **LISTEN**: Download Audio: AudioList field remains on screen.
BR: **LISTEN**  go to SONGS" click three dots, search box opens, key board pops up... enter text. click "Artist"; tap search icon. keyboard goes away, but content is stuck up high instead of moving back down. apparently the keyboard pushes this image up... it doesn't over lay the image.
BR:  **LISTEN** go to Gurudeva's 1970 Master Course. This closes the portal stack and initiates a dbase search after going to card playlist of stack "Listen" the screen is blank. This give the impression that the search is taking forever. but in fact if you go back to the portal and return to the same playlist, the list is there. the dbase search succeeds, the list is inserted and a mobilescroller is created but no content appears. So, I don't think the dbase routine is taking any long time... ergo: it appears to be a screen refresh/rendering issue.

**Comment by jacquegay** [comment]
**JG: Lexicon**: search results field is too short and doesn't scroll because the outer group scrolls instead. Tapping in the alphabet display shows "false" in the search field.
**JG: Educational Insights**: loads with  Results for:_ei" in the search results field. I think this is normal?
**JG: Practice-Daily Lesson:** This is working fine for me on my S5. Everything displays, scrolling works, and I can advance or retreat to the next/previous lesson. Could there be a problem with the particular lesson you looked at? There is no trouble here at all. Was able to leave via the Home button normally and then go back to the lesson again.
JG: Color Meditation: The info field scrolling is jerky. Looks like it needs acceleratedRendering and/or "scrolling" layerMode.
**JG: About the Monastery:** Web widget didn't display properly (small in upper left corner.) Rotating it crashed. However, when returning after a relaunch it behaved fine. There was a problem earlier with a different web view but it didn't crash, right before the web view that did. This looks like memory exhaustion to me, not a problem with the script itself, because it's not repeatable. I'd been working with the app for over an hour without any issues, and other web views were fine.

**Comment by jacquegay** [comment]
BR: the crashes you describe sound like low memory issues, especially since they aren't reliably repeatable. Same with the crash I had in an entirely different place. I'm not sure this can be fixed, since if the phone doesn't have any RAM left there is little we can do.

Editing this: it may not be low memory, it could be memory corruption which may be more likely. This would be something the LC team needs to fix.

**Comment by Brahmanathaswami** [comment]
@jacquegay   Makes no sense to me: we are closing all stacks. the daily lesson is a) 1 image b) text which we process intensively in a script to "type set" it properly... but hardly a RAM hog.... 
How do we monitor RAM usage run time on Android?

**Comment by jacquegay** [comment]
Just edited my comment -- it may not be low memory, it's more likely to be corrupted memory. But I'm just guessing. The fact that it isn't reliably repeatable seems to indicate something is going on behind the scenes.

**Comment by jacquegay** [comment]
You can see what is using memory in the system settings. Every version of Android OS is a little different, but most of the time it's in Developer Options as "Show Running Services". It doesn't look like our app uses much, so low memory probably isn't the issue.

**Comment by HeidiAas** [comment]
test

**Comment by HeidiAas** [comment]
wrote a comment earlier today and hit green comment button, i think hard enough, but am not seeing my comment. can I look for it somewhere?

**Comment by HeidiAas** [comment]
suspect I closed the tab and hadn't hit comment hard enough to enter it

**Comment by Brahmanathaswami** [comment]
@jacquegay Today I rebooted my nexus5 and went tot he app to start testing again. This time I went to the Practice -> Daily lesson right away.. it rendered perfectly... so the I tried to figure what I did before... I was able to reproduce this by moving back to the "Surprise" stack... going to some verses.. then back to the home stack then back to Practice and Daily Lesson. This time the lesson did not appear... I could see a scroller on the right side of the screen.. ... I hit the back button and the lesson suddenly appeared! It was in fact there... no memory issue.. this is some kind or rendingering issue... exact same thing is happening in the listen module. And I think the common scenario the same:

1) go to a stack/card that has a handle that will generate content (in the Audio playlist case, it is a list of title from the dbase; in the case of the daily lesson, a long handler builds a text string to put into the field.
2) the data is inserted into the field
3) then the mobile scroller is created
but something block the display on the whole screen. No memory issue, the scripts ran just fine..

JG: I repeated the steps on my S5. Surprise -> Verses -> view 3 verses -> Home (surprise) -> Home (main portal) ->Daily Lesson. It worked fine, everything appeared. I have a very fast internet connection so there was very little lag though the first verse took a few seconds to appear. The next two showed immediately. Could the problem be the speed of the internet connection? Something timing out maybe?

**Comment by Brahmanathaswami** [comment]
[From Heidi, this is from RC 5]
Surprise --> Audio --> Sambha Sadasiva  --> Did not load --> Top Arrow does nothing
BR: Not an Android issue!  this is a bug in our FetchMedia library.

see issue: #129

**Comment by ActiveThought** [comment]
The app has crashed numerous times on my S7. Sometimes as soon as I have opened the app, other times when I click on any of the menu links, but the crashes are random and I have not been able to recreate them. It does crash quiet often when I swap between apps.

Don't think its due to a memory shortage as my phone has ample and I am not battling with any other apps.

I also had about an hour of constant app usage without any crashes

Some other things I have noticed:

Monestry website shows
- links took ages to open and appeared as though nothing was happening.  
- virtual tours are not responsive
- view blog - browser window was not the correct size

Games
- Cant scroll popup (i button) when in portrait. when I rotated the phone, did not respond properly
- Back button is not visible on all images and made it difficult to go back. Phone's back button did not work either.

Siva's art - images dragable - scroll bar does nothing. images take some time to load and if you click the nav/arrow button before the image loads, the reveal effect plays multiple times instead of just once

Audio- track carries on playing if you navigate away, cant stop the audio. Scrollbar also shows through the search options drop down. 

On some of the pages (like audio) a larger scrollbar was showing to the right of the scrollbar but did nothing.

A couple of the html pages show android's zoom button. 

JG: I don't think it is lack of memory any more either. What version of Android OS are you running? I think the S7 should be on Android N (version 7, Nougat) now, right? I wonder if newer OSs are an issue. I also saw the monastery blog web viewer draw incorrectly, very small, but when I returned to the page it was okay. Right after that is when I crashed when trying to view a different web-based card. So it appears there may still be issues with the LC web widget.

**Comment by Brahmanathaswami** [comment]
Solved: The key was 
a) turn off acceleratedRendering on the old stack
b) open the new stack
c) wait 100 milliseconds.
d) close the old stack
e) Wait again
f) THEN DO NOT TURN on acceleratedRendering in the Preopenstack handler.
g) do it the openStack handler or later.

  set the acceleratedRendering of stack oStackName to false
   
   go  cardOrStackObject  # e.g   go "gems" (or this string)  go card 3 of "gems"   
   wait 100 milliseconds with messages  
   close stack oStackName   
   wait 100 milliseconds with messages
