### ISSUE TITLE
Siva's Art Bugs

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#134]
- [ ] initial call fails and the card open and shows nothing (not always) loading from server...
- [ ]  click next arrow twice triggers reveal to run 2 times in a row.

**Comment by jacquegay** [comment]
The repeated animation is due to LC always implementing nested "lock screen for visual effect" calls even if the screen is already locked. Two taps on the button will nest the calls. You can probably eliminate the issue by checking the lockscreen and exiting the handler if it is true. Or anything else that prevents repeated taps should work too.

**Comment by Brahmanathaswami** [comment]
will have some time to talk? I have 4 of us now "banging on Android" and I need to develop a strategy to get thru this, I could use your insight. I could hire you to fix the things that are can be obviously fixed

**Comment by Brahmanathaswami** [comment]
Completed.
