### ISSUE TITLE
Implement a Delete Icon in the Journal

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#198]
We are saving to many things in the journal. 

The user will want  a way to delete from the journal. I suggest"

1. Put a "minus" sign on the default entry layout.
2. when the click the word "Delete" should up as  button  or icon (will need a border)
3. if they user clicks an the  button, it deletes the item, for now you can change to color the entry field, we don't want to rebuild it them on every deletion. 
4. it they click out side the delete icon it disappears and nothing happends

**Comment by soapdog** [comment]
Working on this.

At first glance, there is no good place in the UI to place those minus and delete buttons per entry. It becomes too cramped and hard to hit.

I'm trying to come up with some solution here.

**Comment by soapdog** [comment]
Also, when did the journal became a substack of Siva-Siva-App.livecode? That sounds odd to me. I'm sure we didn't created it that way, it was supposed to be loaded on demand.

**Comment by soapdog** [comment]
Implemented deletion by using an extra card in the journal stack.

![screencast 2020-12-14 18-53-50](https://user-images.githubusercontent.com/23247/102123560-ec670100-3e3e-11eb-9d50-6de627fe0217.gif)

The card looks the same as the "entries" card but the group that is assembled contains a delete icon instead of the module and favourite icons. The header changed to "Edit Journal".

This is working great inside the IDE, I can't test on devices at the moment.

**Comment by soapdog** [comment]
@Brahmanathaswami waiting for your review.

**Comment by Brahmanathaswami** [comment]
I don,t see you  on Skype or Slack
