### ISSUE TITLE
Tree Nav apply to Stories.livecode

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#251]
We  need to get the tree in all stacks
The method we use so far (from Jacque) is to keep to the "root authority" of the tree in the custom controls stack. We (re)create that array from that there.

If we delete in from anyone module, it will be automatically copied/saved to the  module from "production" 
@bwmilby What do you think?

**Comment by bwmilby** [comment]
The array that is used does need to reside in a stack that never gets unloaded so it is always available.  Also, we should ensure that the widget is a part of all stacks before building the app.  Lastly, script locals should be in a library if they should persist between instances of the widget since each object gets its own copy of behavior script locals.

**Comment by Brahmanathaswami** [comment]
@bwmilby  Downed grade this to "all stacks" to "Stories.livecode"

**Comment by Brahmanathaswami** [comment]
Switch to "daily lesson" as the development environment because we will not be working on the stack
