### ISSUE TITLE
Settings/My Data/Stories: need create/delete Stories

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#264]
- Settings / My  Data / Stories
      -  go to a screen which contains ##Title##  of the Story
      - we should allow them to delete: the folder, all images, are the livecode stack (assuming is presented) from SivaSivaApp/media/stories/ #WhatEverTitleFolder #wipe out

Give the UI something to make it better. That is up to you. The entire "Delete..." is small. It would go for a delete function / slider-DELETE 

it should go by story title

eg

Trek to Siva
Fantastic Kumbha Nasik
Women of India

we should we able to delete that folder which has from title from UI

**Comment by soapdog** [comment]
Working on this.

At first glance, there is no good place in the UI to place those _minus_ and _delete buttons_ per entry. It becomes too cramped and hard to hit.

I'm trying to come up with some solution here.

**Comment by soapdog** [comment]
Also, when did the journal became a substack of `Siva-Siva-App.livecode`? That sounds odd to me. I'm sure we didn't created it that way, it was supposed to be loaded on demand.

**Comment by soapdog** [comment]
Implemented deletion by using an extra card in the journal stack.

![screencast 2020-12-14 18-53-50](https://user-images.githubusercontent.com/23247/102122947-284d9680-3e3e-11eb-854a-1baf9a7cd14d.gif)

The card looks the same as the "entries" card but the group that is assembled contains a delete icon instead of the module and favourite icons. The header changed to "Edit Journal".

This is working great inside the IDE, I can't test on devices at the moment.
